# NumPy Array Copy vs View

In [53]:
# Difference Between Copy and View
# Copy of an array is that the copy is a new array, 
# And the view is just a view of the original array.

In [79]:
import numpy as np
arr = ([1,2,3,4,5])
new_arr = arr.copy() # The copy SHOULD NOT be affected by the changes made to the original array.
arr[0] = 42
print(arr)
print(new_arr)

[42, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


In [77]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view() # The view SHOULD be affected by the changes made to the original array.
arr[1] = 23
print(arr)
print(x)

[ 1 23  3  4  5]
[ 1 23  3  4  5]


In [87]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view() 
x[2]=34  # The original array SHOULD be affected by the changes made to the view.
print(arr)
print(x)

[ 1  2 34  4  5]
[ 1  2 34  4  5]


In [89]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
y = arr.copy()
print(x.base) # The view returns the original array.
print(y.base) # The copy returns None.

[1 2 3 4 5]
None


# NumPy Array Shape
- The shape of an array is the number of elements in each dimension.
- NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.


In [100]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print('Shape of the array:',arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
Shape of the array: (2, 4)


In [108]:
arr = np.array([1,2,3,4],ndmin=5)
print(arr)
print('Shape of the array:',arr.shape)

[[[[[1 2 3 4]]]]]
Shape of the array: (1, 1, 1, 1, 4)


# NumPy Array Reshaping
- Reshaping means changing the shape of an array.
- The shape of an array is the number of elements in each dimension.

In [115]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
new_arr = arr.reshape(4,3)
print(new_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [117]:
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [125]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,9])
newarr = arr.reshape(3, 3)
print(newarr)
print(newarr.base)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [133]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [135]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


# Iterating Arrays
- Iterating means going through elements one by one.
- As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.
- If we iterate on a 1-D array it will go through each element one by one.

In [138]:
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

1
2
3


In [144]:
arr = np.array([[1, 2, 3],[4,5,6]]) # If we iterate on a n-D array it will go through n-1th dimension one by one.
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [146]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [154]:
arr = np.array([[[1, 2, 3], [4, 5, 6],[7,8,9],[10, 11, 12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [156]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
    print(x)


1
2
3
4
5
6
7
8


# Joining NumPy Arrays 
Joining means putting contents of two or more arrays in a single array.

In [159]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
newarr = np.concatenate((arr1,arr2))
newarr

array([1, 2, 3, 4, 5, 6])

In [161]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
newarr = np.concatenate((arr1,arr2),axis=1)
newarr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [165]:
newarr = np.concatenate((arr1,arr2),axis=0)
newarr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [167]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
newarr = np.stack((arr1,arr2),axis = 1)
newarr

array([[1, 4],
       [2, 5],
       [3, 6]])

In [171]:
newarr = np.stack((arr1,arr2),axis = 0)
newarr

array([[1, 2, 3],
       [4, 5, 6]])

In [177]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
newarr = np.hstack((arr1,arr2)) # Stacking Along Rows
newarr

array([1, 2, 3, 4, 5, 6])

In [175]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
newarr = np.vstack((arr1,arr2)) # Stacking Along Columns
newarr

array([[1, 2, 3],
       [4, 5, 6]])

In [179]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
newarr = np.dstack((arr1,arr2)) # Stacking Along Height (depth)
newarr

array([[[1, 4],
        [2, 5],
        [3, 6]]])